app = 'easel-demo'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

  [build.args]

[deploy]
  release_command = ""

[env]
  PHX_HOST = "easel-demo.fly.dev"
  FLY_MACHINE_SIZE = "performance-cpu-1x / 1gb"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'performance'
  cpus = 1
  count = 1
